BEMServer/bemserver-ui

bemserver_ui/extensions/api_client/client.py
bemserver_ui/extensions/api_client/resources.py

Update api client for data completeness

Data completeness api client

---

bemserver_ui/extensions/api_client/exceptions.py

Revert flake8 B903 fix

---

bemserver_ui/static/scripts/modules/components/accordionList.js
bemserver_ui/static/scripts/modules/components/timeseries/selector.js
bemserver_ui/static/scripts/modules/components/tsCompChart.js
bemserver_ui/static/scripts/modules/views/campaigns/selector.js
bemserver_ui/static/scripts/modules/views/structuralElements/explore.js
bemserver_ui/static/scripts/modules/views/timeseries/list.js
bemserver_ui/static/scripts/modules/views/timeseries/manageStructuralElements.js
bemserver_ui/static/styles/app.css
bemserver_ui/static/styles/main.css
bemserver_ui/templates/components/timeseries/selector.html
bemserver_ui/templates/components/users/user_available.html
bemserver_ui/templates/components/users/user_for_group.html
bemserver_ui/templates/macros/items_count.html
bemserver_ui/templates/pages/campaign_scopes/list.html
bemserver_ui/templates/pages/campaigns/list.html
bemserver_ui/templates/pages/campaigns/view.html
bemserver_ui/templates/pages/home.html
bemserver_ui/templates/pages/services/cleanup/list.html
bemserver_ui/templates/pages/services/cleanup/manage.html
bemserver_ui/templates/pages/skeleton.html
bemserver_ui/templates/pages/structural_elements/edit.html
bemserver_ui/templates/pages/structural_elements/properties/list.html
bemserver_ui/templates/pages/timeseries/data/completeness.html
bemserver_ui/templates/pages/timeseries/data/delete.html
bemserver_ui/templates/pages/timeseries/data/explore.html
bemserver_ui/templates/pages/timeseries/edit.html
bemserver_ui/templates/pages/timeseries/list.html
bemserver_ui/templates/pages/timeseries/manage_structural_elements.html
bemserver_ui/templates/pages/timeseries/properties/list.html
bemserver_ui/templates/pages/users/list.html

Upgrade dependencies to latest version:
- bootstrap 5.2.1
- bootstrap icons 1.9.1

Upgrade bootstrap & bootstrap icons

---

bemserver_ui/internal_api/timeseries_data.py
bemserver_ui/static/scripts/modules/components/timeseries/selector.js
bemserver_ui/static/scripts/modules/components/tsChart.js
bemserver_ui/static/scripts/modules/views/timeseries/dataCompleteness.js
bemserver_ui/static/scripts/modules/views/timeseries/dataExplore.js
bemserver_ui/static/scripts/modules/views/timeseries/delete.js
bemserver_ui/templates/pages/timeseries/data/explore.html

- Improve timeseries selector (get both ids and names of selected timeseries)
- Update timeseries explore page to render several timeseries data in chart

Multiple timeseries selection in explore page

---

bemserver_ui/static/scripts/modules/components/time/datetimePicker.js
bemserver_ui/static/scripts/modules/components/time/tzPicker.js

Components impacted:
- Timezone selector
- Datetime picker

Fix es6 components for chrome

---

bemserver_ui/static/scripts/modules/components/tsEnerConsChart.js
bemserver_ui/static/scripts/modules/views/dashboards/energyConsumptionExplore.js
bemserver_ui/static/styles/app.css
bemserver_ui/templates/components/header.html
bemserver_ui/templates/pages/dashboards/energy_consumption/explore.html

Use time xAxis type, rework tooltip and data view to show time depending on period type selection (year only for Yearly period, year/month for monthly over 1 year, etc).

Rework energy consumption dashboard

---

bemserver_ui/extensions/campaign_context.py
bemserver_ui/templates/pages/campaigns/list.html
bemserver_ui/templates/pages/campaigns/view.html
bemserver_ui/templates/pages/home.html
bemserver_ui/templates/pages/services/cleanup/list.html
bemserver_ui/views/campaigns.py
bemserver_ui/views/main.py
bemserver_ui/views/services/cleanup.py

Default home page (or index) is now campaign list, if no campaign is selected.
When a campaign in set as app context, home (or index) page is structural elements explore page.

Change index/home page mechanics

---

bemserver_ui/static/scripts/modules/components/timeseries/bucketWidth.js
bemserver_ui/static/scripts/modules/views/timeseries/dataExplore.js
bemserver_ui/templates/pages/timeseries/data/explore.html

Use this component in TS explore page.
This update follows a rework on TS buckets in BEMServer Core & API.

Add TS bucket ES6 component

---

bemserver_ui/__init__.py
requirements/install.txt
setup.cfg
setup.py

Upgrade API client

---

CHANGELOG.rst
README.rst
requirements/install.txt
setup.py

Prepare for package publishing on PyPI.

Update README, CHANGELOG, setup

---

bemserver_ui/common/tools.py
bemserver_ui/internal_api/analysis.py
bemserver_ui/internal_api/timeseries_data.py
bemserver_ui/views/timeseries/timeseries_data.py
requirements/install.txt
setup.py

- Use last bemserver_api_client package (0.2.0).
- Update timeseries data upload/download to specify CSV format (in API default is now JSON).

Upgrade bemserver_api_client (0.2.0)

---

bemserver_ui/static/scripts/modules/views/timeseries/dataExplore.js
bemserver_ui/views/timeseries/timeseries_data.py

Download CSV chart toolbox feature was broken.
Repaired with last bemserver_api_client version.

Fix timeseries data explore download CSV

---

bemserver_ui/internal_api/services/__init__.py
bemserver_ui/internal_api/services/missing_data.py
bemserver_ui/static/scripts/modules/components/itemsCount.js
bemserver_ui/static/scripts/modules/views/services/missingData/list.js
bemserver_ui/static/scripts/modules/views/services/missingData/manage.js
bemserver_ui/templates/components/sidebar.html
bemserver_ui/templates/pages/services/missing_data/list.html
bemserver_ui/templates/pages/services/missing_data/manage.html
bemserver_ui/views/services/__init__.py
bemserver_ui/views/services/missing_data.py

- Service state for each campaign
- Enable/disable service for a selected campaign

Add check missing data service management pages

---

bemserver_ui/extensions/timezones/__init__.py
bemserver_ui/internal_api/events.py
bemserver_ui/internal_api/structural_elements.py
bemserver_ui/internal_api/timeseries.py
bemserver_ui/static/scripts/modules/views/events/list.js
bemserver_ui/static/scripts/modules/views/events/notifSetup.js
bemserver_ui/static/scripts/modules/views/structuralElements/explore.js
bemserver_ui/templates/pages/events/list.html
bemserver_ui/templates/pages/structural_elements/explore.html
requirements/install.txt
setup.py

Mainly timeseries and events filters rework.

Update following API v0.9.0

---

bemserver_ui/static/scripts/modules/components/time/datetimePicker.js
bemserver_ui/static/scripts/modules/components/time/tzPicker.js
bemserver_ui/static/scripts/modules/components/timeseries/bucketWidth.js
bemserver_ui/templates/pages/timeseries/data/completeness.html
bemserver_ui/templates/pages/timeseries/data/delete.html
bemserver_ui/templates/pages/timeseries/data/explore.html

Use (bootstrap) small size for some filter inputs (timeseries data explore page, ...).

Minor update form inputs

---

bemserver_ui/static/scripts/modules/components/itemsCount.js
bemserver_ui/static/scripts/modules/views/analysis/energyConsumptionConfig.js
bemserver_ui/templates/pages/analysis/energy_consumption/config.html

Fix items count update in energy consumption analysis setup page.

Minor fix analysis setup

---

bemserver_ui/internal_api/__init__.py
bemserver_ui/internal_api/events.py
bemserver_ui/internal_api/notifications.py
bemserver_ui/static/scripts/app.js
bemserver_ui/static/scripts/modules/notifications.js
bemserver_ui/static/scripts/modules/tools/fetcher.js
bemserver_ui/templates/components/header.html

Start implementation of notifications in UI (header notif bell status update)

Notifications header bell icon status

---

README.rst
setup.py

Fix (for PyPI) and update README

Fix README

---

bemserver_ui/internal_api/events.py
bemserver_ui/static/scripts/modules/components/flash.js
bemserver_ui/static/scripts/modules/components/modalConfirm.js
bemserver_ui/static/scripts/modules/components/structuralElements/selector.js
bemserver_ui/static/scripts/modules/components/tree.js
bemserver_ui/static/scripts/modules/tools/fetcher.js
bemserver_ui/static/scripts/modules/views/events/edit.js
bemserver_ui/static/styles/app.css
bemserver_ui/static/styles/tree.css
bemserver_ui/templates/pages/events/edit.html
bemserver_ui/views/events/events.py
bemserver_ui/views/structural_elements/structural_elements.py

- link/unlink timeseries
- link/unlink structural elements (sites, buildings...)

Extend events edit

---

bemserver_ui/static/scripts/modules/components/timeseries/selector.js
bemserver_ui/static/scripts/modules/components/tree.js
bemserver_ui/static/scripts/modules/views/analysis/energyConsumptionConfig.js
bemserver_ui/static/scripts/modules/views/events/edit.js
bemserver_ui/static/scripts/modules/views/timeseries/dataCompleteness.js
bemserver_ui/static/scripts/modules/views/timeseries/dataExplore.js
bemserver_ui/static/scripts/modules/views/timeseries/delete.js
bemserver_ui/static/styles/app.css
bemserver_ui/static/styles/main.css
bemserver_ui/templates/macros/components/ts_selector.html
bemserver_ui/templates/pages/analysis/energy_consumption/config.html
bemserver_ui/templates/pages/analysis/energy_consumption/explore.html
bemserver_ui/templates/pages/campaign_scopes/view.html
bemserver_ui/templates/pages/events/edit.html
bemserver_ui/templates/pages/events/list.html
bemserver_ui/templates/pages/structural_elements/explore.html
bemserver_ui/templates/pages/timeseries/data/completeness.html
bemserver_ui/templates/pages/timeseries/data/delete.html
bemserver_ui/templates/pages/timeseries/data/explore.html
bemserver_ui/templates/pages/timeseries/list.html
bemserver_ui/templates/pages/timeseries/manage_structural_elements.html
bemserver_ui/templates/pages/users/view.html

- Manage a unique selected timeseries list (with all timeseries attributes)
- Disable timeseries selection if allowed limit is reached
- Use structural element selector as location filter

Improve timeseries selector

---

bemserver_ui/internal_api/analysis/energy_consumption/setup.py
bemserver_ui/static/scripts/modules/views/analysis/energyConsumption/setup.js
bemserver_ui/templates/pages/analysis/energy_consumption/setup.html
bemserver_ui/views/analysis/energy_consumption.py
requirements/install.txt
setup.py

- Upgrade API client
- Update energy consumption setup page

Upgrade API client (>=0.12.0,<0.13.0)

---

bemserver_ui/extensions/error_handlers.py
bemserver_ui/static/scripts/modules/components/flash.js
bemserver_ui/static/scripts/modules/tools/dict.js
bemserver_ui/static/scripts/modules/tools/fetcher.js
bemserver_ui/templates/macros/flash.html
requirements/install.txt
setup.py

- Upgrade API client
- Improve 409 status code management in displayed messages

Upgrade API client (>=0.12.1, <0.13.0)

---

bemserver_ui/static/scripts/modules/tools/fetcher.js
bemserver_ui/static/scripts/modules/views/events/edit.js

- Fix fetcher error messages build
- Fix edit events links error messages

Fix fetcher

---

bemserver_ui/extensions/plugins.py
bemserver_ui/templates/components/sidebar/sidebar.html
bemserver_ui/templates/macros/components/sidebar.html
tests/test_extensions_plugins.py

Delegate "building" plugin sidebar entries logic (whether it should be displayed or not, depending on campaign context...) inside plugin themselves.

Improve plugins system extension

---

bemserver_ui/static/scripts/modules/formController.js
bemserver_ui/static/scripts/modules/views/structuralElements/explore.js
bemserver_ui/static/styles/main.css
bemserver_ui/templates/pages/structural_elements/create.html
bemserver_ui/templates/pages/structural_elements/edit.html
bemserver_ui/views/structural_elements/structural_elements.py

- Update create/edit site page
- Update explore sites page

Add lat/long on sites

---

bemserver_ui/internal_api/services/__init__.py
bemserver_ui/internal_api/services/weather_data.py
bemserver_ui/internal_api/structural_elements.py
bemserver_ui/static/scripts/modules/components/time/datetimePicker.js
bemserver_ui/static/scripts/modules/views/services/weatherData/manage.js
bemserver_ui/templates/components/sidebar/sidebar_services.html
bemserver_ui/templates/pages/services/weather_data/manage.html
bemserver_ui/views/services/__init__.py
bemserver_ui/views/services/weather_data.py

- Manage weather data service state for each site of a campaign
- Manually fetch weather data (from external web service, oikolab)

Add weather data service page

---

bemserver_ui/internal_api/analysis/degree_days.py

NaN values replaced by None in API responses

Fix analysis degree days

---

bemserver_ui/static/scripts/modules/components/timeseries/selector.js
bemserver_ui/templates/macros/components/ts_selector.html

Add a quick access to "unselect all" feature, next to main search button.
(as done in structural elements selector)

Update timeseries selector component

---

bemserver_ui/common/time.py
bemserver_ui/internal_api/timeseries/data.py
bemserver_ui/static/scripts/modules/components/charts/tsChartExplore.js
bemserver_ui/static/scripts/modules/components/time/datetimePicker.js
bemserver_ui/static/scripts/modules/components/timeseries/bucketWidth.js
bemserver_ui/static/scripts/modules/components/timeseries/selector.js
bemserver_ui/static/scripts/modules/formController.js
bemserver_ui/static/scripts/modules/views/timeseries/data/explore.js
bemserver_ui/static/styles/app.css
bemserver_ui/templates/pages/timeseries/data/explore.html
bemserver_ui/views/timeseries/data.py
tests/test_common_time.py

- rework user experience: simplify inputs (period selection, aggregation...) and "hide" complex settings (timezone, timeseries data states)
- chart is dynamically updated
- chart series are added by selecting timeseries
- chart series can be customized (type, color, y-axis position, style...)

Rework timeseries data explore page

---

bemserver_ui/internal_api/timeseries/data.py
bemserver_ui/static/scripts/modules/components/charts/tsChartExplore.js
bemserver_ui/static/scripts/modules/components/timeseries/selector.js
bemserver_ui/static/scripts/modules/views/events/list.js
bemserver_ui/static/scripts/modules/views/structuralElements/explore.js
bemserver_ui/static/scripts/modules/views/timeseries/data/explore.js
bemserver_ui/static/scripts/modules/views/timeseries/manageStructuralElements.js
bemserver_ui/templates/components/sidebar/sidebar_tsdata.html
bemserver_ui/templates/pages/structural_elements/explore.html
bemserver_ui/templates/pages/timeseries/manage_structural_elements.html

- Delay page auto refresh when applying search filters
- Fix timeseries data explore chart update
- UX updates (structural elements explore page, sidebar)

Various updates

---

bemserver_ui/static/scripts/modules/components/charts/tsChartCompleteness.js
bemserver_ui/static/scripts/modules/components/charts/tsChartDegreeDays.js
bemserver_ui/static/scripts/modules/components/charts/tsChartEnergyConsumption.js
bemserver_ui/static/scripts/modules/components/charts/tsChartWeather.js
bemserver_ui/templates/pages/skeleton.html

- echarts 5.4.2
- bootstrap 5.3.0
- bootstrap-icons 1.10.5

Upgrade JS dependencies

---

src/bemserver_ui/internal_api/analysis/completeness.py
src/bemserver_ui/static/scripts/modules/components/charts/common.js
src/bemserver_ui/static/scripts/modules/components/charts/tsChartCompleteness.js
src/bemserver_ui/static/scripts/modules/tools/time.js
src/bemserver_ui/static/scripts/modules/views/timeseries/data/completeness.js
src/bemserver_ui/templates/pages/timeseries/data/completeness.html

- Fixes leap year management (rework period selection)
- Compute completeness chart height in order to show all timeseries at once

Rework completeness

---

src/bemserver_ui/internal_api/analysis/degree_days.py
src/bemserver_ui/settings.py
src/bemserver_ui/static/scripts/modules/components/charts/common.js
src/bemserver_ui/static/scripts/modules/components/charts/tsChartCompleteness.js
src/bemserver_ui/static/scripts/modules/components/charts/tsChartDegreeDays.js
src/bemserver_ui/static/scripts/modules/views/analysis/degreeDays.js

- Remove obsolete JSON_SORT_KEYS config var from app settings
- Fix degree days compare chart (categories order)

Fix json sort keys

---

src/bemserver_ui/extensions/error_handlers.py
src/bemserver_ui/extensions/flask_helpers.py
src/bemserver_ui/static/scripts/modules/components/flashMessage.js
src/bemserver_ui/static/scripts/modules/tools/fetcher.js
src/bemserver_ui/static/scripts/modules/views/notifications/setup.js
src/bemserver_ui/templates/components/flash_messages.html

Manage validation errors details

Fix flash message regression

---

README.rst
pyproject.toml
requirements/install.txt
requirements/tests.in
requirements/tests.txt
src/bemserver_ui/extensions/api_client.py
src/bemserver_ui/extensions/auth.py
src/bemserver_ui/extensions/campaign_context.py
src/bemserver_ui/extensions/error_handlers.py
src/bemserver_ui/settings.py
src/bemserver_ui/views/auth.py
src/bemserver_ui/views/users.py

Uses bemserver-api 0.24.0 and bemserver-api-client 0.21.1 to implement bearer token authentication.

Manage bearer token authentication (JWT)

---

src/bemserver_ui/common/analysis.py
src/bemserver_ui/common/time.py
src/bemserver_ui/internal_api/analysis/__init__.py
src/bemserver_ui/internal_api/analysis/completeness.py
src/bemserver_ui/internal_api/analysis/parameters.py
src/bemserver_ui/static/scripts/modules/components/charts/common.js
src/bemserver_ui/static/scripts/modules/components/charts/tsChartCompleteness.js
src/bemserver_ui/static/scripts/modules/components/timeseries/selector.js
src/bemserver_ui/static/scripts/modules/tools/time.js
src/bemserver_ui/static/scripts/modules/tools/utils.js
src/bemserver_ui/static/scripts/modules/views/events/edit.js
src/bemserver_ui/static/scripts/modules/views/timeseries/data/completeness.js
src/bemserver_ui/static/scripts/modules/views/timeseries/semanticSetup.js
src/bemserver_ui/templates/macros/components/ts_selector.html
src/bemserver_ui/templates/pages/timeseries/data/completeness.html
src/bemserver_ui/views/timeseries/data.py
tests/test_common_analysis.py
tests/test_common_time.py

- improve timeseries selector
- rework timeseries data completeness page to use query args

Update completeness page (query args)

---

src/bemserver_ui/static/scripts/modules/tools/time.js
src/bemserver_ui/static/scripts/modules/views/events/list.js
src/bemserver_ui/templates/pages/events/list.html

Add timeseries data explore link in event detail modal

Update events page

---

src/bemserver_ui/static/scripts/modules/tools/utils.js
src/bemserver_ui/static/scripts/modules/views/timeseries/list.js
src/bemserver_ui/templates/pages/timeseries/list.html
src/bemserver_ui/views/timeseries/timeseries.py

Timeseries list page: add filters on timeseries properties

Add timeseries property filters

---

src/bemserver_ui/internal_api/timeseries/data.py
src/bemserver_ui/static/scripts/modules/components/charts/tsChartExplore.js
src/bemserver_ui/static/scripts/modules/views/timeseries/data/compareStates.js
src/bemserver_ui/static/scripts/modules/views/timeseries/data/explore.js
src/bemserver_ui/templates/components/sidebar/sidebar_tsdata.html
src/bemserver_ui/templates/pages/timeseries/data/compare_states.html
src/bemserver_ui/views/timeseries/data.py

- Add timeseries data compare data states page
- Update timeseries explore chart

Add timeseries data compare data states feature

---

src/bemserver_ui/static/scripts/modules/components/charts/tsChartExplore.js
src/bemserver_ui/static/scripts/modules/components/timeseries/selector.js
src/bemserver_ui/static/scripts/modules/tools/compress.js
src/bemserver_ui/static/scripts/modules/views/timeseries/data/compareStates.js
src/bemserver_ui/static/scripts/modules/views/timeseries/data/explore.js

- Improve timeseries data explore reload from url (include chart settings)
- Fix timeseries data chart dataview
- Fix timeseries data compare states

Improve & fix ts data charts
